/** 活动类别配置 */
const CATEGORIES = {
  music:      { icon: '🎵', label: '音乐', color: '#8B5CF6' },
  sport:      { icon: '⚽', label: '运动', color: '#10B981' },
  exhibition: { icon: '🖼️', label: '展览', color: '#3B82F6' },
  food:       { icon: '🍔', label: '美食', color: '#EF4444' },
  social:     { icon: '💬', label: '社交', color: '#EC4899' },
};

/** 广州 mock 活动（x/y 为地图截图上的百分比位置） */
const ACTIVITIES = [
  {
    id: 'a1',
    name: '广美毕业作品展',
    category: 'exhibition',
    x: 63, y: 58,
    distance: '8.2km',
    time: '进行中',
    status: 'ongoing',
    rating: 4.8,
    reviewCount: 326,
    address: '广州大学城广州美术学院',
    district: '番禺',
    thumb: 'linear-gradient(135deg,#667eea,#764ba2)',
    desc: '研究生与本科生毕业联展，免费参观。',
  },
  {
    id: 'a2',
    name: '永庆坊周末创意市集',
    category: 'food',
    x: 36, y: 40,
    distance: '1.8km',
    time: '6月14日 10:00',
    status: 'upcoming',
    rating: 4.6,
    reviewCount: 189,
    address: '荔湾区恩宁路永庆坊',
    district: '荔湾',
    thumb: 'linear-gradient(135deg,#f093fb,#f5576c)',
    desc: '手作、文创与广府小吃，适合周末闲逛。',
  },
  {
    id: 'a3',
    name: '二沙岛周末飞盘局',
    category: 'sport',
    x: 50, y: 36,
    distance: '2.5km',
    time: '进行中',
    status: 'ongoing',
    rating: 4.5,
    reviewCount: 94,
    address: '越秀区二沙岛体育公园',
    district: '越秀',
    thumb: 'linear-gradient(135deg,#11998e,#38ef7d)',
    desc: '新手友好，现场可借盘，每周六下午。',
  },
  {
    id: 'a4',
    name: '太古仓 Live 音乐夜',
    category: 'music',
    x: 41, y: 46,
    distance: '2.1km',
    time: '6月14日 19:30',
    status: 'upcoming',
    rating: 4.7,
    reviewCount: 215,
    address: '海珠区革新路太古仓码头',
    district: '海珠',
    thumb: 'linear-gradient(135deg,#4facfe,#00f2fe)',
    desc: '江边露天 live，本地独立乐队演出。',
  },
  {
    id: 'a5',
    name: '南越王博物院特展',
    category: 'exhibition',
    x: 46, y: 30,
    distance: '1.2km',
    time: '进行中',
    status: 'ongoing',
    rating: 4.9,
    reviewCount: 512,
    address: '越秀区解放北路867号',
    district: '越秀',
    thumb: 'linear-gradient(135deg,#fa709a,#fee140)',
    desc: '「尼罗河的赠礼」古埃及文物数字艺术展。',
  },
  {
    id: 'a6',
    name: '珠江新城美食快闪',
    category: 'food',
    x: 57, y: 33,
    distance: '0.8km',
    time: '6月15日 11:00',
    status: 'upcoming',
    rating: 4.2,
    reviewCount: 67,
    address: '天河区花城广场北区',
    district: '天河',
    thumb: 'linear-gradient(135deg,#ff9a9e,#fecfef)',
    desc: '网红餐饮快闪，免费试吃名额有限。',
  },
  {
    id: 'a7',
    name: '沙面街头爵士',
    category: 'music',
    x: 39, y: 44,
    distance: '2.8km',
    time: '6月13日 20:00',
    status: 'upcoming',
    rating: 4.4,
    reviewCount: 143,
    address: '荔湾区沙面大街',
    district: '荔湾',
    thumb: 'linear-gradient(135deg,#a18cd1,#fbc2eb)',
    desc: '欧式建筑背景下的街头爵士表演。',
  },
  {
    id: 'a8',
    name: '广州塔夜跑团',
    category: 'sport',
    x: 52, y: 42,
    distance: '3.5km',
    time: '6月14日 20:00',
    status: 'upcoming',
    rating: 4.3,
    reviewCount: 88,
    address: '海珠区广州塔西广场',
    district: '海珠',
    thumb: 'linear-gradient(135deg,#30cfd0,#330867)',
    desc: '5km 沿江夜跑，集合后统一出发。',
  },
  {
    id: 'a9',
    name: '东山口独立书展',
    category: 'exhibition',
    x: 53, y: 32,
    distance: '1.5km',
    time: '进行中',
    status: 'ongoing',
    rating: 4.1,
    reviewCount: 56,
    address: '越秀区东山口恤孤院路',
    district: '越秀',
    thumb: 'linear-gradient(135deg,#ffecd2,#fcb69f)',
    desc: '独立出版与小众杂志，文艺青年聚集地。',
  },
  {
    id: 'a10',
    name: '琶醍啤酒社交夜',
    category: 'social',
    x: 47, y: 49,
    distance: '3.8km',
    time: '6月14日 18:00',
    status: 'upcoming',
    rating: 4.5,
    reviewCount: 201,
    address: '海珠区阅江路琶醍啤酒文化创意区',
    district: '海珠',
    thumb: 'linear-gradient(135deg,#f6d365,#fda085)',
    desc: '精酿品鉴 + 陌生人破冰桌游，需提前预约。',
  },
  {
    id: 'a11',
    name: '天河路街头滑板赛',
    category: 'sport',
    x: 61, y: 34,
    distance: '1.0km',
    time: '6月15日 15:00',
    status: 'upcoming',
    rating: 4.0,
    reviewCount: 42,
    address: '天河区正佳广场外广场',
    district: '天河',
    thumb: 'linear-gradient(135deg,#84fab0,#8fd3f4)',
    desc: '业余滑手交流赛，围观免费。',
  },
  {
    id: 'a12',
    name: '荔湾湖太极晨练社',
    category: 'social',
    x: 34, y: 43,
    distance: '2.0km',
    time: '进行中',
    status: 'ongoing',
    rating: 4.6,
    reviewCount: 77,
    address: '荔湾区龙津西路荔湾湖公园',
    district: '荔湾',
    thumb: 'linear-gradient(135deg,#cfd9df,#e2ebf0)',
    desc: '长者太极与年轻人冥想体验，免费参与。',
  },
];

/** 是否高分活动 */
function isHighScore(activity) {
  return activity.rating >= 4.5;
}

/** 渲染星级 HTML */
function renderStars(rating) {
  const full = Math.floor(rating);
  const half = rating - full >= 0.3;
  let html = '';
  for (let i = 0; i < 5; i++) {
    if (i < full) html += '<span class="star on">★</span>';
    else if (i === full && half) html += '<span class="star half">★</span>';
    else html += '<span class="star">★</span>';
  }
  return html;
}
